# Generated by Django 4.1.2 on 2022-11-05 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('photo', models.ImageField(upload_to='cars')),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('kronolive_times_url', models.CharField(max_length=512)),
                ('kronolive_inscribed_url', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('dorsal', models.CharField(max_length=16)),
                ('copilot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copilot', to='core.competitormodel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventmodel')),
                ('pilot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot', to='core.competitormodel')),
            ],
        ),
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SectionTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_time', models.DurationField()),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inscriptionmodel')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sectionmodel')),
            ],
        ),
    ]
