# Generated by Django 4.1.2 on 2022-11-05 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_inscriptionmodel_pilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionmodel',
            name='copilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copilot_inscription', to='core.competitormodel'),
        ),
        migrations.AlterField(
            model_name='inscriptionmodel',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_inscription', to='core.competitormodel'),
        ),
    ]
