# Generated by Django 4.1.2 on 2022-11-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_inscriptionmodel_copilot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectiontimemodel',
            unique_together={('section', 'inscription', 'section_time')},
        ),
    ]
