# Generated by Django 4.1.2 on 2023-02-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sectiontimemodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
    ]
