# Generated by Django 4.1.2 on 2023-02-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eventmodel_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='category',
            field=models.CharField(choices=[('RALLY', 'Rally'), ('HILL-CLIMB', 'Hill Climb'), ('AUTO-CROSS', 'Auto Cross'), ('KARTING', 'Karting')], default='RALLY', max_length=16),
        ),
    ]
