# Generated by Django 4.1.2 on 2023-02-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_eventmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='provider_data',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='provider_name',
            field=models.CharField(choices=[('KRONOLIVE', 'Kronolive')], default='KRONOLIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='kronolive_inscribed_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='kronolive_times_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
