# Generated by Django 4.1.2 on 2023-02-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_eventmodel_provider_data_eventmodel_provider_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='kronolive_inscribed_url',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='kronolive_times_url',
        ),
    ]
