# Generated by Django 4.1.2 on 2023-02-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_eventmodel_kronolive_inscribed_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='provider_data',
            field=models.JSONField(default=dict),
        ),
    ]
