# Generated by Django 4.1.2 on 2023-02-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_eventmodel_provider_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='category',
            field=models.CharField(choices=[('RALLY', 'Rally'), ('HILL-CLIMB', 'Hill Climb'), ('AUTO-CROSS', 'Auto Cross'), ('KARTING', 'Karting')], max_length=16),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='provider_name',
            field=models.CharField(choices=[('KRONOLIVE', 'Kronolive')], max_length=16),
        ),
    ]
