# Generated by Django 4.1.2 on 2023-02-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_eventmodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='provider_name',
            field=models.CharField(choices=[('KRONOLIVE', 'Kronolive'), ('KRONOBOT', 'Kronobot')], default='KRONOBOT', max_length=16),
        ),
    ]
