# Generated by Django 4.1.2 on 2023-02-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_eventmodel_provider_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='date',
            new_name='start_date',
        ),
    ]
