# Generated by Django 4.1.2 on 2023-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_eventmodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='end_date',
            field=models.DateField(),
        ),
    ]
