# Generated by Django 4.1.2 on 2023-02-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_eventmodel_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
