# Generated by Django 4.1.2 on 2023-02-28 16:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_eventmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
